# Generated by Django 4.2 on 2024-08-08 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('numero_processo', models.CharField(max_length=20, unique=True, verbose_name='Número do Processo')),
                ('requerente', models.CharField(max_length=120, verbose_name='Requerente')),
                ('assunto', models.CharField(max_length=120, verbose_name='Assunto')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('observacao', models.TextField(blank=True, max_length=400, verbose_name='Observações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
