# Generated by Django 4.2 on 2024-08-13 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('sigla_setor', models.CharField(help_text='Digite a sigla do setor.', max_length=5, unique=True, verbose_name='Setor')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('data_entrada', models.DateField(verbose_name='Data de entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('setor_servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_documentos.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('numero_processo', models.CharField(max_length=20, unique=True, verbose_name='Número do Processo')),
                ('requerente', models.CharField(max_length=120, verbose_name='Requerente')),
                ('assunto', models.CharField(choices=[('ABERTURA DE INSCRICAO IMOBILIARIA AREA RURAL', 'Abertura de inscrição imobiliária área rural'), ('ABERTURA DE MATRICULA', 'Abertura de matrícula'), ('ABERTURA INSCRICAO IMOBILIARIA', 'Abertura inscrição imobiliária'), ('AQUISICAO DE MATERIAL PERMANENTE', 'Aquisição de material permanente'), ('APROVACAO DE PROJETOS ARQUITETONICO', 'Aprovação de projetos arquitetônico'), ('AUTO DE INFRACAO', 'Auto de infração'), ('AVERBACAO', 'Averbação'), ('AVERBACAO EX. OFICIO', 'Averbação ex. ofício'), ('BENEFICIO DO PRODES', 'Benefício do Prodes'), ('CANCELAMENTO DE DEBITO', 'Cancelamento de débito'), ('CERTIDAO', 'Certidão'), ('CERTIDAO DE DEMOLICAO', 'Certidão de demolição'), ('CERTIDAO DE EDIFICACAO', 'Certidão de edificação'), ('CERTIDAO DE VALOR VENAL', 'Certidão de valor venal'), ('CERTIDAO EDIFICACAO – LEI 13.865/2019', 'Certidão edificação – Lei 13.865/2019'), ('CONTRATACAO DE SERVICO', 'Contratação de serviço'), ('DEMANDA DE SOFTWARES DO SETOR', 'Demanda de softwares do setor'), ('DESAFETACAO', 'Desafetação'), ('DESAPROPRIACAO', 'Desapropriação'), ('DESM/REMEM/DESDOBRO E AVERBACAO', 'Desm/remem/desdobro e averbação'), ('DOACAO DE AREA', 'Doação de área'), ('DOACAO EM PAGAMENTO', 'Doação em pagamento'), ('ISENCAO DE IPTU', 'Isenção de IPTU'), ('ISENCAO DE ITBI RURAL', 'Isenção de ITBI rural'), ('ISENCAO DE ITBI URBANO', 'Isenção de ITBI urbano'), ('INDENIZACAO', 'Indenização'), ('LEVANTAMENTO TOPOGRAFICO', 'Levantamento topográfico'), ('LOTEAMENTO', 'Loteamento'), ('NOTIFICACAO DE AUTO DE INFRACAO', 'Notificação de auto de infração'), ('OUTRO ASSUNTO', 'Outro assunto'), ('PARECERES', 'Pareceres'), ('PARECER IMOBILIARIO', 'Parecer imobiliário'), ('PARCELAMENTO', 'Parcelamento'), ('PERMUTA', 'Permuta'), ('PERMISSAO DE USO DE AREA PUBLICA', 'Permissão de uso de área pública'), ('PRESTACAO DE SERVICOS DIVERSOS', 'Prestação de serviços diversos'), ('PROCESSO DE APOSENTADORIA E PENSIONISTA', 'Processo de aposentadoria e pensionista'), ('PROCESSO DE DEBITO', 'Processo de débito'), ('REGULARIZACAO', 'Regularização'), ('REGULARIZACAO FUNDIARIA', 'Regularização fundiária'), ('REMEMBRAMENTO/DESDOBRO', 'Remembramento/desdobro'), ('REVISAO DE DADOS CADASTRAIS', 'Revisão de dados cadastrais'), ('REAVALIACAO DE ITBI RURAL', 'Reavaliação de ITBI rural'), ('REAVALIACAO DE ITBI URBANO', 'Reavaliação de ITBI urbano'), ('SUBSTITUICAO DE RESPONS TRIBUTARIO', 'Substituição de respons tributário'), ('SUBSTITUICAO DE PROJETO', 'Substituição de projeto'), ('VERIFICACAO', 'Verificação'), ('VERIFICACAO DE IPTU', 'Verificação de IPTU'), ('VERIFICACAO DE I.P.T.U.', 'Verificação de I.P.T.U.'), ('REQUERIMENTO', 'Requerimento')], max_length=255, verbose_name='Tipo de Assunto')),
                ('data_abertura_processo', models.DateField(help_text='Informe a data de abertura do Processo.', verbose_name='Data de abertura')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Arquivado', 'Arquivado'), ('Concluido', 'Concluído')], default='Aberto', max_length=9, verbose_name='Status')),
                ('data_conclusao_processo', models.DateField(blank=True, help_text='Informe a data de conclusão do Processo.', null=True, verbose_name='Data de conclusão')),
                ('observacao', models.TextField(blank=True, max_length=400, verbose_name='Observações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('setor_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_documentos.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('numero_oficio', models.CharField(max_length=20, unique=True, verbose_name='Número do Ofício')),
                ('assunto', models.CharField(max_length=100, verbose_name='Assunto')),
                ('data_oficio', models.DateField(help_text='Digite a data do ofício.', verbose_name='Data do ofício')),
                ('prazo', models.PositiveSmallIntegerField(help_text='Quantidade de dias.', verbose_name='Prazo')),
                ('data_vencimento', models.DateField(blank=True, editable=False, verbose_name='Data de vencimento')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Arquivado', 'Arquivado'), ('Atendido', 'Atendido')], default='Aberto', max_length=9, verbose_name='Status')),
                ('data_conclusao_oficio', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('observacao', models.TextField(blank=True, max_length=400, verbose_name='Observações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('setor_oficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard_documentos.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
            },
        ),
    ]
