# Generated by Django 4.2 on 2024-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Nao', 'Não')], default='Nao', max_length=3, verbose_name='Recebido'),
        ),
    ]
